val it : unit = ()
exception Foo
val foldl : (('a * 'b) -> 'a) -> 'a -> 'b list -> 'c = fn
val sum : int list -> 'a = fn
Exception Foo[<TTY listener>:1,11 to 1,13] raised
Entering debugger, commands: q : quit (return to listener),  ? : more help
Current (innermost) stack frame:
foldl argument 2 []
Debugger> 