exception DontFail
val hasFailed : bool ref = ref(false)
test succeeded
